parameters:
    sendgrid.email_address: '%env(SENDGRID_EMAIL_ADDRESS)%'
    sendgrid.apikey: '%env(SENDGRID_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\Controller\:
        resource: '../src/Application/Controller'
        tags: ['controller.service_arguments']

    Application\Handler\:
        resource: '../src/Application/Handler'
        tags:
            - { name: tactician.handler, typehints: true }

    Infrastructure\SendGrid\SendGridMailer:
        arguments: ['%sendgrid.apikey%']